package com.zhaolei.material.admin.dao.graduation;

import com.zhaolei.material.admin.dao.base.ISqlMapper;
import com.zhaolei.material.admin.domain.dao.OrganizationDO;
import org.apache.ibatis.annotations.Param;

/**
 * @author ZHAOLEI
 */
public interface OrganizationMapper extends ISqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Wed Mar 18 12:20:33 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Wed Mar 18 12:20:33 CST 2020
     */
    int insert(OrganizationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Wed Mar 18 12:20:33 CST 2020
     */
    int insertSelective(OrganizationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Wed Mar 18 12:20:33 CST 2020
     */
    OrganizationDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Wed Mar 18 12:20:33 CST 2020
     */
    int updateByPrimaryKeySelective(OrganizationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Wed Mar 18 12:20:33 CST 2020
     */
    int updateByPrimaryKey(OrganizationDO record);

    /**
     * 根据组织名称查询组织信息
     * @param organizationName
     * @return
     */

    OrganizationDO selectByOrgName(@Param("orgName") String organizationName);
}